services:
  markdown-converter:
    build: 
      context: .
      args:
        - GIT_COMMIT=${GIT_COMMIT:-unknown}
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    restart: unless-stopped