services:
  markdown-converter:
    build: 
      context: .
      args:
        - GIT_COMMIT=${GIT_COMMIT:-unknown}
    container_name: markdown-converter
    restart: always
    networks:
      - markdown-converter-network
    volumes:
      - ./server/downloads:/usr/src/app/server/downloads
      - ./server/temp:/usr/src/app/server/temp
    environment:
      - NODE_ENV=production

networks:
  markdown-converter-network:
    external: true
    name: nginx-proxy-manager