/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexSimpleRouteImport } from './routes/index-simple'
import { Route as IndexRouteImport } from './routes/index'

const IndexSimpleRoute = IndexSimpleRouteImport.update({
  id: '/index-simple',
  path: '/index-simple',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/index-simple': typeof IndexSimpleRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/index-simple': typeof IndexSimpleRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/index-simple': typeof IndexSimpleRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/index-simple'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/index-simple'
  id: '__root__' | '/' | '/index-simple'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  IndexSimpleRoute: typeof IndexSimpleRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/index-simple': {
      id: '/index-simple'
      path: '/index-simple'
      fullPath: '/index-simple'
      preLoaderRoute: typeof IndexSimpleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  IndexSimpleRoute: IndexSimpleRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
